export const ACTION_RESET_APP = "ACTION_RESET_APP";
export const ALL_PRODUCT_LIST = "ALL_PRODUCT_LIST";
export const ASSIGN_INITIAL_DATA = "ASSIGN_INITIAL_DATA";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_TO_CART = "REMOVE_PRODUCT_TO_CART";
export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
export const UPDATE_CART_PRODUCT_LIST = "UPDATE_CART_PRODUCT_LIST";
